services:
  app:
    build:
      context: .
      target: app
    ports:
      - "8000:8000"
    environment:
      UV_PROJECT_ENVIRONMENT: /opt/venv
      VIPS_WARNING: "0"
    restart: unless-stopped
